Repository pagarme/pilot, pull requests merged in 2018-12, with the labels that each got.

#1038 Fix event-stream and flatmap-stream dependencies
  yarn.lock
Labels: bug-fix, devs, review-needed

#1039 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: devs, pilot

#1040 components: add input with password strength as component
  packages/pilot/package.json
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/components/PasswordInput/index.js
  packages/pilot/src/components/PasswordInput/style.css
  packages/pilot/stories/components/PasswordInput/index.js
  packages/pilot/stories/components/index.js
  yarn.lock
Labels: devs, pilot, review-needed
