Repository pagarme/pilot, pull requests merged in 2019-06, with the labels that each got.

#1249 PR: Fix de small issues encontradas na Dash de Recebedores
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/containers/Filter/index.js
  packages/pilot/src/containers/RecipientDetails/index.js
  packages/pilot/src/containers/RecipientTable/index.js
  packages/pilot/src/containers/RecipientTable/statusLegend.js
  packages/pilot/src/containers/RecipientTable/tableColumns.js
  packages/pilot/src/models/recipientStatusLegends.js
  packages/pilot/src/pages/Recipients/Search/Search.js
  packages/pilot/src/pages/Recipients/Search/reducer.js
  packages/pilot/stories/containers/RecipientDetails/index.js
Labels: cos:standard, devs

#1257 antecipation: update translate
  packages/pilot/public/locales/pt/translations.json
Labels: cos:standard, devs

#1259 release 0.14.2 - 17/06/2019
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/errors/index.js
  packages/pilot/src/errors/pendingRiskAnalysis.js
  packages/pilot/src/pages/Account/actions/epic.js
Labels: cos:fixed-date, review-needed, v0.14.2-rc1

#1260 settings: add possibility to change api version
  packages/pilot/package.json
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/containers/Settings/Company/GeneralInfoTab/ApiKey/index.js
  packages/pilot/src/containers/Settings/Company/GeneralInfoTab/Versions/index.js
  packages/pilot/src/containers/Settings/Company/GeneralInfoTab/Versions/style.css
  packages/pilot/src/containers/Settings/Company/GeneralInfoTab/index.js
  packages/pilot/src/containers/Settings/Company/index.js
  packages/pilot/src/pages/CompanySettings/index.js
  yarn.lock
Labels: cos:fixed-date, cos:standard

#1265 Fix transaction paid amount
  packages/cockpit/src/transactions/search/query.js
  packages/cockpit/src/transactions/search/query.test.js
Labels: cockpit, cos:expedite, review-needed

#1271 Refactor configurations style
  packages/pilot/src/components/ApiKey/index.js
Labels: cos:expedite, devs, pilot
