Repository pagarme/pilot, pull requests merged in 2020-07, with the labels that each got.

#1668 EXP-97 chore: hidden api key to customers of payment link
  packages/pilot/src/containers/Settings/Company/GeneralInfoTab/index.js
  packages/pilot/src/containers/Settings/Company/index.js
  packages/pilot/src/pages/CompanySettings/index.js
Labels: cos:intangible, pilot, review-needed

#1680 EXP-143 Add zoopim tags
  packages/pilot/src/pages/Account/actions/epic.js
  packages/pilot/src/vendor/zopim.js
Labels: cos:standard

#1687 EXP-95 chore: remove onboarding company payment-link-app
  packages/pilot/src/pages/EmptyState/EmptyState.js
Labels: business, cos:standard

#1691 EXP-148: Padroniza verificação do tipo de company
  packages/pilot/src/containers/Balance/index.js
  packages/pilot/src/containers/Header/index.js
  packages/pilot/src/containers/Settings/Company/index.js
  packages/pilot/src/containers/Sidebar/index.js
  packages/pilot/src/pages/Account/actions/epic.js
  packages/pilot/src/pages/CompanySettings/index.js
  packages/pilot/src/pages/EmptyState/EmptyState.js
  packages/pilot/src/validation/isPaymentLink.js
Labels: cos:standard, link.me web

#1694 EXP-173 transaction: add customer name fallback in list
  packages/pilot/src/containers/TransactionsList/tableColumns.js
Labels: cos:standard

#1695 EXP-163 :Remover botão de reprocessamento de transação para clientes link.me na pilot
  packages/pilot/src/containers/TransactionDetails/index.js
  packages/pilot/src/pages/Transactions/Details/Details.js
Labels: link.me web
