Repository pagarme/pilot, pull requests merged in 2020-04, with the labels that each got.

#1594 Atualizar plataformas suportadas pelo Pagar.me
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/pages/Onboarding/machine/data/supportedPlatforms.json
  packages/pilot/src/pages/Onboarding/machine/settings.js
Labels: cos:standard, devs, help-wanted, pilot, review-needed

#1596 onboarding: update others state on new question
  packages/pilot/src/containers/Onboarding/index.js
Labels: devs, help-wanted, review-needed

#1601 Release v0.24.1
  packages/pilot/src/pages/Account/actions/epic.js
  packages/pilot/src/pages/Withdraw/index.js
Labels: bug-fix, cos:standard, devs

#1605 Onboarding/add question
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/components/OnboardingBackground/styles.css
  packages/pilot/src/pages/Onboarding/machine/settings.js
Labels: devs, help-wanted, pilot, review-needed

#1607 Release/v0.24.2
  packages/pilot/public/locales/pt/translations.json
  packages/pilot/src/components/OnboardingBackground/styles.css
  packages/pilot/src/pages/Onboarding/machine/settings.js
Labels: v0.24.2
